<a href="https://colab.research.google.com/github/sandipbnkr/DemoCodeNucleus/blob/main/numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#### np.linspace(): used to create a sequence of numbers with constant spacing or linear spacing between 2 numbers

In [3]:
"""
Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].
"""
#default it returns 50 numbers
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [ ]:
12.6122449 - 12.87755102

-0.26530612

In [ ]:
14.20408163-  14.46938776

-0.2653061300000008

In [ ]:
#if we want only 20 numbers betwen 1-15
np.linspace(1,15,20)
# stop is inclusive

array([ 1.        ,  1.73684211,  2.47368421,  3.21052632,  3.94736842,
        4.68421053,  5.42105263,  6.15789474,  6.89473684,  7.63157895,
        8.36842105,  9.10526316,  9.84210526, 10.57894737, 11.31578947,
       12.05263158, 12.78947368, 13.52631579, 14.26315789, 15.        ])

In [ ]:
#if we set endpoint=False
#then stop wont be a part of output
np.linspace(1,15,20,endpoint=False)

array([ 1. ,  1.7,  2.4,  3.1,  3.8,  4.5,  5.2,  5.9,  6.6,  7.3,  8. ,
        8.7,  9.4, 10.1, 10.8, 11.5, 12.2, 12.9, 13.6, 14.3])

In [ ]:
#to check difference btwn 2 values set retstep=True
np.linspace(1,15,20,endpoint=False,retstep=True)

(array([ 1. ,  1.7,  2.4,  3.1,  3.8,  4.5,  5.2,  5.9,  6.6,  7.3,  8. ,
         8.7,  9.4, 10.1, 10.8, 11.5, 12.2, 12.9, 13.6, 14.3]),
 0.7)

## Generate sin wave using linspace

In [ ]:
x = np.linspace(2,40,100)

y = np.sin(x)

In [ ]:
# lineplot
import matplotlib.pyplot as plt

plt.plot(x,y,'--r')

### np.append():to append elements at the end


In [5]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [ ]:
"""
Signature: np.append(arr, values, axis=None)
Docstring:
Append values to the end of an array. (temp.)
"""
np.append(a,400)

array([ 10,  20,  30,  40, 400])

In [ ]:
a

array([10, 20, 30, 40])

In [ ]:
# append list
np.append(a,[3,4,5])

array([10, 20, 30, 40,  3,  4,  5])

In [ ]:
np.append(a,range(3,8))

array([10, 20, 30, 40,  3,  4,  5,  6,  7])

## np.cumsum: cummulative sum

In [6]:
a

array([10, 20, 30, 40])

In [ ]:
#Ex.[1,2,3,5]=1+2=3+3=6+5=11
np.cumsum(a)

array([ 10,  30,  60, 100])

In [ ]:
team1 = [2,10,5]

In [ ]:
np.cumsum(team1)

array([ 2, 12, 17])

In [18]:
b = np.arange(24).reshape(4,6)



In [ ]:
np.cumsum(b,axis=0) #columnwise

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14, 16],
       [18, 21, 24, 27, 30, 33],
       [36, 40, 44, 48, 52, 56]])

### np.cumprod: cummulative product

In [24]:
# assignment: for all values,for columns,for rows
np.cumprod(b,axis=1)


array([[       0,        0,        0,        0,        0,        0],
       [       6,       42,      336,     3024,    30240,   332640],
       [      12,      156,     2184,    32760,   524160,  8910720],
       [      18,      342,     6840,   143640,  3160080, 72681840]])

## np.delete: to delete an element from an array


In [ ]:
"""
Signature: np.delete(arr, obj, axis=None)
arr: means an array from which we want to delete elements
obj: index of element to delete
Docstring:
Return a new array with sub-arrays along an axis deleted. For a one
dimensional array, this returns those entries not returned by
"""
a

array([10, 20, 30, 40])

In [ ]:
np.delete(a,2)

array([10, 20, 40])

In [ ]:
np.delete(a,-1)

array([10, 20, 30])

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
#operations gives u an output but its temp. output not permanent

In [ ]:
np.delete(b,3) # in genral case it will convert array into 1D and will delete element at that index

array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
#remove a row: row starting with 12
np.delete(b,2,axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
#remove a last column
np.delete(b,-1,axis=1)

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

## np.insert: too add element in between

In [ ]:
"""
Signature: np.insert(arr, obj, values, axis=None)
Docstring:
Insert values along the given axis before the given indices.
"""
#add 300 between 20 and 30
a

array([10, 20, 30, 40])

In [ ]:
np.insert(a,2,300)

array([ 10,  20, 300,  30,  40])

In [ ]:
# insert 100 after 40
np.insert(a,4,100)

array([ 10,  20,  30,  40, 100])

In [ ]:
np.append(a,100)

array([ 10,  20,  30,  40, 100])

In [ ]:
#insert 900 before 10
np.insert(a,0,900)

array([900,  10,  20,  30,  40])

In [ ]:
#2D
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
#insert new data before 2nd column
np.insert(b,3,100)

array([  0,   1,   2, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
# insert all 1's in column
np.insert(b,1,[1,1,1,1],axis=1)

array([[ 0,  1,  1,  2,  3,  4,  5],
       [ 6,  1,  7,  8,  9, 10, 11],
       [12,  1, 13, 14, 15, 16, 17],
       [18,  1, 19, 20, 21, 22, 23]])

In [ ]:
np.insert(b,2,[6,6,6,6,6,6],axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 6,  6,  6,  6,  6,  6],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [27]:
#insert a new data in each column and requiremnt is to add 500 everywhere
np.insert(b,1,[666,666,666,666],axis=1)


array([[  0, 666,   1,   2,   3,   4,   5],
       [  6, 666,   7,   8,   9,  10,  11],
       [ 12, 666,  13,  14,  15,  16,  17],
       [ 18, 666,  19,  20,  21,  22,  23]])

## np.where: conidition based conversion we can carry out

In [ ]:
"""
Docstring:
np.where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

if condition is True return x else return y
"""
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
# return 0 if value<12
np.where(b<12,0,b)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
#value<12 +ve and remaining -ve
np.where(b<12,'+ve','-ve')

array([['+ve', '+ve', '+ve', '+ve', '+ve', '+ve'],
       ['+ve', '+ve', '+ve', '+ve', '+ve', '+ve'],
       ['-ve', '-ve', '-ve', '-ve', '-ve', '-ve'],
       ['-ve', '-ve', '-ve', '-ve', '-ve', '-ve']], dtype='<U3')

In [ ]:
np.where(b>19,b,-b)

In [ ]:
gen = ['male','female','male','female']
gen = np.array(gen)

In [ ]:
gen

array(['male', 'female', 'male', 'female'], dtype='<U6')

In [ ]:
np.where(gen=='male',0,1)

array([0, 1, 0, 1])

In [ ]:
import seaborn as sns
t = sns.load_dataset('titanic')
np.where(t.sex=='male',0,1)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,

In [ ]:
t.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64